# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e26dba42c4b32c919083a89f10b345457f5566336f4bcd672875b9744289528db7599ec558e2870a64cacdf62210660c11537df498756e88ed2cbb46226d3768

test:
  secret_key_base: 3b3512efe2bf271c31824220b253435156027ec4ae3f90d07bf4882daa7101f26171841b14520364c02418773a018c699db6080c4b888e599e3358b928e0a97e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
